// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3KtP7wC6tWqCzk9NnlIbeM4bkulW-Jhs',
    appId: '1:680319540872:web:bfd4881f7aa48006b4093d',
    messagingSenderId: '680319540872',
    projectId: 'the-180-project',
    authDomain: 'the-180-project.firebaseapp.com',
    storageBucket: 'the-180-project.firebasestorage.app',
    measurementId: 'G-SH5XR7W3E1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3KtP7wC6tWqCzk9NnlIbeM4bkulW-Jhs',
    appId: '1:680319540872:web:a1d7fd871e722c8ab4093d',
    messagingSenderId: '680319540872',
    projectId: 'the-180-project',
    authDomain: 'the-180-project.firebaseapp.com',
    storageBucket: 'the-180-project.firebasestorage.app',
    measurementId: 'G-48N79F09P2',
  );
}
